### ISSUE TITLE
GooglePlayのapkに問題がある可能性

### ISSUE THREAD

**Issue by ghost** [AioiLight/EnableGPlayWithPC#6]
以下の足りない権限
android.permission.DUMP
android.permission.WRITE_SECURE_SETTINGS
を付与し、GooglePlayの最新バージョンに入れ替えたところ、エラーが発生しなかった。
※使用したGooglePlayはＡｐｋＰｕｒｅからダウンロードしたものを使用した。

**Comment by AioiLight** [comment]
そもそもこのリポジトリにapkファイルは含まれていません、ご確認ください
